import puppeteer from 'puppeteer-core';
const CHROME = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const wait = (ms) => new Promise((r) => setTimeout(r, ms));
setTimeout(() => { console.error('WATCHDOG 120s'); process.exit(2); }, 120000).unref();
const b = await puppeteer.launch({ executablePath: CHROME, headless: 'new', args: ['--no-sandbox'] });
const p = await b.newPage();
await p.setViewport({ width: 390, height: 844, isMobile: true });
p.on('pageerror', (e) => console.log('PAGEERROR:', String(e.message).slice(0,300)));
p.on('console', (m) => { if (m.type()==='error'||m.type()==='warning') console.log('CONSOLE['+m.type()+']:', m.text().slice(0,300)); });
await p.evaluateOnNewDocument(() => { localStorage.setItem('gw-onboarded', '1'); });
await p.goto('http://localhost:4173/', { waitUntil: 'networkidle2', timeout: 60000 });
await p.waitForFunction('window.__gw !== undefined', { timeout: 45000 });
async function pick(sel, q) { await p.type(sel, q); try { await p.waitForSelector('#suggestions .sugg', { timeout: 8000 }); await p.click('#suggestions .sugg'); } catch { await p.focus(sel); await p.keyboard.press('Enter'); } await wait(500); }
await pick('#toInput', 'Costco Lehi');
await pick('#fromInput', 'Pleasant Grove Utah');
await p.waitForFunction('window.__ghostwayDebug?.routed === true', { timeout: 40000 });
await wait(800);
console.log('engineReady:', await p.evaluate(() => window.__gw._engineReady));
console.log('engine flag:', await p.evaluate(() => window.__ghostwayEngine));
const handle = await p.evaluate(() => { const m = window.__gw.map.map; const src = m.getSource('waypoint'); const f = src && src._data ? src._data.features : []; return f[0] && f[0].geometry.coordinates; });
console.log('handle:', JSON.stringify(handle));
const pt = await p.evaluate((c) => { const px = window.__gw.map.map.project(c); return { x: px.x, y: px.y }; }, handle);
console.log('screen pos:', JSON.stringify(pt));
await p.mouse.move(pt.x, pt.y); await wait(150);
await p.mouse.down();
await p.mouse.move(pt.x + 40, pt.y, { steps: 4 });
await p.mouse.move(pt.x + 80, pt.y, { steps: 4 });
await p.mouse.move(pt.x + 110, pt.y, { steps: 4 });
await wait(150);
await p.mouse.up();
await wait(3000);
console.log('after drag — viaRoute:', await p.evaluate(() => window.__ghostwayDebug?.viaRoute));
console.log('after drag — viaSource:', await p.evaluate(() => window.__ghostwayDebug?.viaSource));
console.log('after drag — waypoint state:', await p.evaluate(() => JSON.stringify(window.__gw.state.waypoint)));
console.log('after drag — status text:', await p.evaluate(() => document.querySelector('#status')?.textContent || 'none'));
try { await Promise.race([b.close(), wait(5000)]); } catch {}
process.exit(0);
